login_task:
  description: >
    Log into the CRDC QA portal using login.gov. The credentials will be injected at runtime.
  expected_output: >
    A successful login message or URL verification
  agent: login_agent
  input_direct: true

navigate_task:
  description: >
    Navigate to the submission request part of the portal
  expected_output: >
    A successful navigation
  agent: navigate_agent
  input_direct: true

find_latest_sr_task:
  description: >
    Search for the latest submission from specific user and open it for review
  expected_output: >
    Successfully opened the latest submission
  agent: find_latest_sr_agent
  input_direct: true

approve_sr_task:
  description: >
    Approve the submission request by navigating through all sections and clicking approve.
  expected_output: >
    The submission request is approved
  agent: approve_sr_agent

